# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
    source_path: app/javascript
    source_entry_path: packs
    public_root_path: public
    public_output_path: packs
    cache_path: tmp/cache/webpacker
    check_yarn_integrity: false
    webpack_compile_output: true

    # Additional paths webpack should look up modules
    resolved_paths: []

    # Reload manifest.json on all requests so we reload latest compiled packs
    cache_manifest: false

    # Extract and emit a css file
    extract_css: false

    static_assets_extensions:
        - .jpg
        - .jpeg
        - .png
        - .gif
        - .tiff
        - .ico
        - .svg
        - .eot
        - .otf
        - .ttf
        - .woff
        - .woff2

development:
    <<: *default
    compile: true

    # Verifies that versions and hashed value of the package contents in the project's package.json
    check_yarn_integrity: true

    # Reference plugins
    dev_server:
        host: localhost
        port: 3035
        https: false
        hmr: false
        inline: true
        overlay: true
        compress: true
        disable_host_check: true
        use_local_ip: false
        public: localhost:3035
        public_path: /packs/
        poll: 1000
        hmr_host: localhost
        https_key: /etc/ssl/private/ssl-cert-snakeoil.key
        https_cert: /etc/ssl/certs/ssl-cert-snakeoil.pem

test:
    <<: *default
    compile: true

    # Compile test packs to a separate directory
    public_output_path: packs-test

production:
    <<: *default

    # Production depends on precompilation of packs prior to booting for performance.
    compile: false

    # Extract and emit a css file
    extract_css: true

    cache_manifest: true
